### ISSUE TITLE
Merge not done correctly

### ISSUE THREAD

**Issue by srki-pravi-frki** [CynicRus/Isometric-Minesweeper#3]
https://github.com/CynicRus/Isometric-Minesweeper/blob/1a928aa8da3dddadb2755bd80114175e860646ea/main.cpp#L151

**Comment by CynicRus** [comment]
Thank you!

**Comment by srki-pravi-frki** [comment]
I'm teaching a C++ class for the teenage kids, and I will be using your example to showcase a game made in C++ :)
